"""Create user

Revision ID: 18d8768597f9
Revises: 4bfb1765502c
Create Date: 2023-08-07 22:59:05.259000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d8768597f9'
down_revision = '4bfb1765502c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
